# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import listing_pb2 as listing__pb2


class ListingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStocksInExchange = channel.unary_stream(
        '/listing.Listing/GetStocksInExchange',
        request_serializer=listing__pb2.ExchangeRequest.SerializeToString,
        response_deserializer=listing__pb2.StockListing.FromString,
        )
    self.GetStockListing = channel.unary_unary(
        '/listing.Listing/GetStockListing',
        request_serializer=listing__pb2.StockRequest.SerializeToString,
        response_deserializer=listing__pb2.StockListing.FromString,
        )


class ListingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStocksInExchange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStockListing(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ListingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStocksInExchange': grpc.unary_stream_rpc_method_handler(
          servicer.GetStocksInExchange,
          request_deserializer=listing__pb2.ExchangeRequest.FromString,
          response_serializer=listing__pb2.StockListing.SerializeToString,
      ),
      'GetStockListing': grpc.unary_unary_rpc_method_handler(
          servicer.GetStockListing,
          request_deserializer=listing__pb2.StockRequest.FromString,
          response_serializer=listing__pb2.StockListing.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'listing.Listing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
