version: '3'

services:
  postgres:
    image: 'postgres:latest'
  api:
    build:
      dockerfile: Dockerfile
      context: ./data_api
    environment:
      - PSUSER=postgres
      - PHOST=postgres
      - PSDATABASE=postgres
      - PSPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "4000:5000"

