# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: option_params.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='option_params.proto',
  package='option_params',
  syntax='proto3',
  serialized_options=_b('\242\002\002OP'),
  serialized_pb=_b('\n\x13option_params.proto\x12\roption_params\"\x89\x01\n\x0cOptionParams\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x17\n\x0funderlyingConId\x18\x02 \x01(\x01\x12\x14\n\x0ctradingClass\x18\x03 \x01(\t\x12\x12\n\nmultiplier\x18\x04 \x01(\x05\x12\x13\n\x0b\x65xpirations\x18\x05 \x03(\t\x12\x0f\n\x07strikes\x18\x06 \x03(\x01\"\"\n\x07Request\x12\x17\n\x0funderlyingConId\x18\x01 \x01(\x01\"\x07\n\x05\x45mpty\"\x19\n\tTimestamp\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x16\n\x06Result\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t2\x9b\x01\n\x13OptionParamsService\x12\x42\n\tGetRecord\x12\x16.option_params.Request\x1a\x1b.option_params.OptionParams\"\x00\x12@\n\tAddRecord\x12\x1b.option_params.OptionParams\x1a\x14.option_params.Empty\"\x00\x42\x05\xa2\x02\x02OPb\x06proto3')
)




_OPTIONPARAMS = _descriptor.Descriptor(
  name='OptionParams',
  full_name='option_params.OptionParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='option_params.OptionParams.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='underlyingConId', full_name='option_params.OptionParams.underlyingConId', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tradingClass', full_name='option_params.OptionParams.tradingClass', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='option_params.OptionParams.multiplier', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expirations', full_name='option_params.OptionParams.expirations', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strikes', full_name='option_params.OptionParams.strikes', index=5,
      number=6, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=176,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='option_params.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='underlyingConId', full_name='option_params.Request.underlyingConId', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=212,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='option_params.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=221,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='Timestamp',
  full_name='option_params.Timestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='option_params.Timestamp.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=248,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='option_params.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='option_params.Result.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=272,
)

DESCRIPTOR.message_types_by_name['OptionParams'] = _OPTIONPARAMS
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Timestamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OptionParams = _reflection.GeneratedProtocolMessageType('OptionParams', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONPARAMS,
  '__module__' : 'option_params_pb2'
  # @@protoc_insertion_point(class_scope:option_params.OptionParams)
  })
_sym_db.RegisterMessage(OptionParams)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'option_params_pb2'
  # @@protoc_insertion_point(class_scope:option_params.Request)
  })
_sym_db.RegisterMessage(Request)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'option_params_pb2'
  # @@protoc_insertion_point(class_scope:option_params.Empty)
  })
_sym_db.RegisterMessage(Empty)

Timestamp = _reflection.GeneratedProtocolMessageType('Timestamp', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMP,
  '__module__' : 'option_params_pb2'
  # @@protoc_insertion_point(class_scope:option_params.Timestamp)
  })
_sym_db.RegisterMessage(Timestamp)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'option_params_pb2'
  # @@protoc_insertion_point(class_scope:option_params.Result)
  })
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None

_OPTIONPARAMSSERVICE = _descriptor.ServiceDescriptor(
  name='OptionParamsService',
  full_name='option_params.OptionParamsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=275,
  serialized_end=430,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecord',
    full_name='option_params.OptionParamsService.GetRecord',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_OPTIONPARAMS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddRecord',
    full_name='option_params.OptionParamsService.AddRecord',
    index=1,
    containing_service=None,
    input_type=_OPTIONPARAMS,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPTIONPARAMSSERVICE)

DESCRIPTOR.services_by_name['OptionParamsService'] = _OPTIONPARAMSSERVICE

# @@protoc_insertion_point(module_scope)
