# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import option_params_pb2 as option__params__pb2


class OptionParamsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRecord = channel.unary_unary(
        '/option_params.OptionParamsService/GetRecord',
        request_serializer=option__params__pb2.Request.SerializeToString,
        response_deserializer=option__params__pb2.OptionParams.FromString,
        )
    self.AddRecord = channel.unary_unary(
        '/option_params.OptionParamsService/AddRecord',
        request_serializer=option__params__pb2.OptionParams.SerializeToString,
        response_deserializer=option__params__pb2.Empty.FromString,
        )


class OptionParamsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRecord(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OptionParamsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRecord': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecord,
          request_deserializer=option__params__pb2.Request.FromString,
          response_serializer=option__params__pb2.OptionParams.SerializeToString,
      ),
      'AddRecord': grpc.unary_unary_rpc_method_handler(
          servicer.AddRecord,
          request_deserializer=option__params__pb2.OptionParams.FromString,
          response_serializer=option__params__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'option_params.OptionParamsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
