# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import contract_details_pb2 as contract__details__pb2


class ContractDetailsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetContractDetails = channel.unary_unary(
        '/contract_details.ContractDetailsService/GetContractDetails',
        request_serializer=contract__details__pb2.Request.SerializeToString,
        response_deserializer=contract__details__pb2.ContractDetails.FromString,
        )
    self.AddContractDetails = channel.unary_unary(
        '/contract_details.ContractDetailsService/AddContractDetails',
        request_serializer=contract__details__pb2.ContractDetails.SerializeToString,
        response_deserializer=contract__details__pb2.Empty.FromString,
        )


class ContractDetailsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetContractDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddContractDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ContractDetailsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetContractDetails': grpc.unary_unary_rpc_method_handler(
          servicer.GetContractDetails,
          request_deserializer=contract__details__pb2.Request.FromString,
          response_serializer=contract__details__pb2.ContractDetails.SerializeToString,
      ),
      'AddContractDetails': grpc.unary_unary_rpc_method_handler(
          servicer.AddContractDetails,
          request_deserializer=contract__details__pb2.ContractDetails.FromString,
          response_serializer=contract__details__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'contract_details.ContractDetailsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
