# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import historical_data_pb2 as historical__data__pb2


class HistoricalDataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOneHistoricalData = channel.unary_stream(
        '/historical_data.HistoricalData/GetOneHistoricalData',
        request_serializer=historical__data__pb2.Request.SerializeToString,
        response_deserializer=historical__data__pb2.BarData.FromString,
        )
    self.GetManyHistoricalData = channel.stream_stream(
        '/historical_data.HistoricalData/GetManyHistoricalData',
        request_serializer=historical__data__pb2.Request.SerializeToString,
        response_deserializer=historical__data__pb2.BarData.FromString,
        )
    self.AddHistoricalData = channel.unary_unary(
        '/historical_data.HistoricalData/AddHistoricalData',
        request_serializer=historical__data__pb2.HistoricalDataToAdd.SerializeToString,
        response_deserializer=historical__data__pb2.Empty.FromString,
        )
    self.GetHeadTimeStamp = channel.unary_unary(
        '/historical_data.HistoricalData/GetHeadTimeStamp',
        request_serializer=historical__data__pb2.Request.SerializeToString,
        response_deserializer=historical__data__pb2.Result.FromString,
        )
    self.GetStartDb = channel.unary_unary(
        '/historical_data.HistoricalData/GetStartDb',
        request_serializer=historical__data__pb2.Request.SerializeToString,
        response_deserializer=historical__data__pb2.Result.FromString,
        )
    self.GetEndDb = channel.unary_unary(
        '/historical_data.HistoricalData/GetEndDb',
        request_serializer=historical__data__pb2.Request.SerializeToString,
        response_deserializer=historical__data__pb2.Result.FromString,
        )


class HistoricalDataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOneHistoricalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetManyHistoricalData(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddHistoricalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetHeadTimeStamp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStartDb(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetEndDb(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HistoricalDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOneHistoricalData': grpc.unary_stream_rpc_method_handler(
          servicer.GetOneHistoricalData,
          request_deserializer=historical__data__pb2.Request.FromString,
          response_serializer=historical__data__pb2.BarData.SerializeToString,
      ),
      'GetManyHistoricalData': grpc.stream_stream_rpc_method_handler(
          servicer.GetManyHistoricalData,
          request_deserializer=historical__data__pb2.Request.FromString,
          response_serializer=historical__data__pb2.BarData.SerializeToString,
      ),
      'AddHistoricalData': grpc.unary_unary_rpc_method_handler(
          servicer.AddHistoricalData,
          request_deserializer=historical__data__pb2.HistoricalDataToAdd.FromString,
          response_serializer=historical__data__pb2.Empty.SerializeToString,
      ),
      'GetHeadTimeStamp': grpc.unary_unary_rpc_method_handler(
          servicer.GetHeadTimeStamp,
          request_deserializer=historical__data__pb2.Request.FromString,
          response_serializer=historical__data__pb2.Result.SerializeToString,
      ),
      'GetStartDb': grpc.unary_unary_rpc_method_handler(
          servicer.GetStartDb,
          request_deserializer=historical__data__pb2.Request.FromString,
          response_serializer=historical__data__pb2.Result.SerializeToString,
      ),
      'GetEndDb': grpc.unary_unary_rpc_method_handler(
          servicer.GetEndDb,
          request_deserializer=historical__data__pb2.Request.FromString,
          response_serializer=historical__data__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'historical_data.HistoricalData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
