# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_data.proto',
  package='sendrequest',
  syntax='proto3',
  serialized_options=_b('\242\002\002RD'),
  serialized_pb=_b('\n\x12request_data.proto\x12\x0bsendrequest\"\xcf\x02\n\x08\x43ontract\x12\r\n\x05\x63onId\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0f\n\x07secType\x18\x03 \x01(\t\x12\x10\n\x08\x65xchange\x18\x04 \x01(\t\x12\x17\n\x0fprimaryExchange\x18\x05 \x01(\t\x12\x10\n\x08\x63urrency\x18\x06 \x01(\t\x12$\n\x1clastTradeDateOrContractMonth\x18\x07 \x01(\t\x12\x0e\n\x06strike\x18\x08 \x01(\x02\x12\r\n\x05right\x18\t \x01(\t\x12\x12\n\nmultiplier\x18\n \x01(\t\x12\x13\n\x0blocalSymbol\x18\x0b \x01(\t\x12\x14\n\x0ctradingClass\x18\x0c \x01(\t\x12\x16\n\x0eincludeExpired\x18\r \x01(\x08\x12\x11\n\tsecIdType\x18\x0e \x01(\t\x12\r\n\x05secId\x18\x0f \x01(\t\x12\x18\n\x10\x63omboLegsDescrip\x18\x10 \x01(\t\"T\n\x16\x43ontractDetailsRequest\x12\x11\n\trequestId\x18\x01 \x01(\x05\x12\'\n\x08\x63ontract\x18\x02 \x01(\x0b\x32\x15.sendrequest.Contract\"\xd3\x01\n\x15HistoricalDataRequest\x12\'\n\x08\x63ontract\x18\x01 \x01(\x0b\x32\x15.sendrequest.Contract\x12\x13\n\x0b\x65ndDateTime\x18\x02 \x01(\t\x12\x16\n\x0e\x64urationString\x18\x03 \x01(\t\x12\x16\n\x0e\x62\x61rSizeSetting\x18\x04 \x01(\t\x12\x12\n\nwhatToShow\x18\x05 \x01(\t\x12\x0e\n\x06useRTH\x18\x06 \x01(\x05\x12\x12\n\nformatDate\x18\x07 \x01(\x05\x12\x14\n\x0ckeepUpToDate\x18\x08 \x01(\x08\"U\n\x16\x46undamentalDataRequest\x12\'\n\x08\x63ontract\x18\x01 \x01(\x0b\x32\x15.sendrequest.Contract\x12\x12\n\nreportType\x18\x02 \x01(\t\"\x19\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\x08\x32\x8d\x02\n\x0bRequestData\x12T\n\x16RequestContractDetails\x12#.sendrequest.ContractDetailsRequest\x1a\x13.sendrequest.Status\"\x00\x12R\n\x15RequestHistoricalData\x12\".sendrequest.HistoricalDataRequest\x1a\x13.sendrequest.Status\"\x00\x12T\n\x16RequestFundamentalData\x12#.sendrequest.FundamentalDataRequest\x1a\x13.sendrequest.Status\"\x00\x42\x05\xa2\x02\x02RDb\x06proto3')
)




_CONTRACT = _descriptor.Descriptor(
  name='Contract',
  full_name='sendrequest.Contract',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conId', full_name='sendrequest.Contract.conId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='sendrequest.Contract.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secType', full_name='sendrequest.Contract.secType', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='sendrequest.Contract.exchange', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='primaryExchange', full_name='sendrequest.Contract.primaryExchange', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='sendrequest.Contract.currency', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastTradeDateOrContractMonth', full_name='sendrequest.Contract.lastTradeDateOrContractMonth', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strike', full_name='sendrequest.Contract.strike', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='right', full_name='sendrequest.Contract.right', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiplier', full_name='sendrequest.Contract.multiplier', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='localSymbol', full_name='sendrequest.Contract.localSymbol', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tradingClass', full_name='sendrequest.Contract.tradingClass', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='includeExpired', full_name='sendrequest.Contract.includeExpired', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secIdType', full_name='sendrequest.Contract.secIdType', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secId', full_name='sendrequest.Contract.secId', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comboLegsDescrip', full_name='sendrequest.Contract.comboLegsDescrip', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=371,
)


_CONTRACTDETAILSREQUEST = _descriptor.Descriptor(
  name='ContractDetailsRequest',
  full_name='sendrequest.ContractDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='sendrequest.ContractDetailsRequest.requestId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract', full_name='sendrequest.ContractDetailsRequest.contract', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=457,
)


_HISTORICALDATAREQUEST = _descriptor.Descriptor(
  name='HistoricalDataRequest',
  full_name='sendrequest.HistoricalDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract', full_name='sendrequest.HistoricalDataRequest.contract', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endDateTime', full_name='sendrequest.HistoricalDataRequest.endDateTime', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='durationString', full_name='sendrequest.HistoricalDataRequest.durationString', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='barSizeSetting', full_name='sendrequest.HistoricalDataRequest.barSizeSetting', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whatToShow', full_name='sendrequest.HistoricalDataRequest.whatToShow', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='useRTH', full_name='sendrequest.HistoricalDataRequest.useRTH', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='formatDate', full_name='sendrequest.HistoricalDataRequest.formatDate', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keepUpToDate', full_name='sendrequest.HistoricalDataRequest.keepUpToDate', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=671,
)


_FUNDAMENTALDATAREQUEST = _descriptor.Descriptor(
  name='FundamentalDataRequest',
  full_name='sendrequest.FundamentalDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract', full_name='sendrequest.FundamentalDataRequest.contract', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reportType', full_name='sendrequest.FundamentalDataRequest.reportType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=673,
  serialized_end=758,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='sendrequest.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='sendrequest.Status.message', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=760,
  serialized_end=785,
)

_CONTRACTDETAILSREQUEST.fields_by_name['contract'].message_type = _CONTRACT
_HISTORICALDATAREQUEST.fields_by_name['contract'].message_type = _CONTRACT
_FUNDAMENTALDATAREQUEST.fields_by_name['contract'].message_type = _CONTRACT
DESCRIPTOR.message_types_by_name['Contract'] = _CONTRACT
DESCRIPTOR.message_types_by_name['ContractDetailsRequest'] = _CONTRACTDETAILSREQUEST
DESCRIPTOR.message_types_by_name['HistoricalDataRequest'] = _HISTORICALDATAREQUEST
DESCRIPTOR.message_types_by_name['FundamentalDataRequest'] = _FUNDAMENTALDATAREQUEST
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Contract = _reflection.GeneratedProtocolMessageType('Contract', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACT,
  __module__ = 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:sendrequest.Contract)
  ))
_sym_db.RegisterMessage(Contract)

ContractDetailsRequest = _reflection.GeneratedProtocolMessageType('ContractDetailsRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTRACTDETAILSREQUEST,
  __module__ = 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:sendrequest.ContractDetailsRequest)
  ))
_sym_db.RegisterMessage(ContractDetailsRequest)

HistoricalDataRequest = _reflection.GeneratedProtocolMessageType('HistoricalDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _HISTORICALDATAREQUEST,
  __module__ = 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:sendrequest.HistoricalDataRequest)
  ))
_sym_db.RegisterMessage(HistoricalDataRequest)

FundamentalDataRequest = _reflection.GeneratedProtocolMessageType('FundamentalDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _FUNDAMENTALDATAREQUEST,
  __module__ = 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:sendrequest.FundamentalDataRequest)
  ))
_sym_db.RegisterMessage(FundamentalDataRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'request_data_pb2'
  # @@protoc_insertion_point(class_scope:sendrequest.Status)
  ))
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None

_REQUESTDATA = _descriptor.ServiceDescriptor(
  name='RequestData',
  full_name='sendrequest.RequestData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=788,
  serialized_end=1057,
  methods=[
  _descriptor.MethodDescriptor(
    name='RequestContractDetails',
    full_name='sendrequest.RequestData.RequestContractDetails',
    index=0,
    containing_service=None,
    input_type=_CONTRACTDETAILSREQUEST,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestHistoricalData',
    full_name='sendrequest.RequestData.RequestHistoricalData',
    index=1,
    containing_service=None,
    input_type=_HISTORICALDATAREQUEST,
    output_type=_STATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestFundamentalData',
    full_name='sendrequest.RequestData.RequestFundamentalData',
    index=2,
    containing_service=None,
    input_type=_FUNDAMENTALDATAREQUEST,
    output_type=_STATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REQUESTDATA)

DESCRIPTOR.services_by_name['RequestData'] = _REQUESTDATA

# @@protoc_insertion_point(module_scope)
