"""empty message

Revision ID: 6b62058f1f20
Revises: 8214568604af
Create Date: 2019-10-24 00:31:09.103798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b62058f1f20'
down_revision = '8214568604af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_statements', sa.Column('report_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_statements', 'report_type')
    # ### end Alembic commands ###
