"""initial migration

Revision ID: 8214568604af
Revises: 
Create Date: 2019-08-06 06:20:36.820493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8214568604af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_reports',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('xml', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'insert_date')
    )
    op.create_table('contract_details',
    sa.Column('contractId', sa.Integer(), nullable=False),
    sa.Column('marketName', sa.String(), nullable=True),
    sa.Column('minTick', sa.Float(), nullable=True),
    sa.Column('orderTypes', sa.String(), nullable=True),
    sa.Column('validExchanges', sa.String(), nullable=True),
    sa.Column('priceMagnifier', sa.Integer(), nullable=True),
    sa.Column('underConId', sa.Integer(), nullable=True),
    sa.Column('longName', sa.String(), nullable=True),
    sa.Column('contractMonth', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('timeZoneId', sa.String(), nullable=True),
    sa.Column('tradingHours', sa.String(), nullable=True),
    sa.Column('liquidHours', sa.String(), nullable=True),
    sa.Column('evRule', sa.String(), nullable=True),
    sa.Column('evMultiplier', sa.Integer(), nullable=True),
    sa.Column('mdSizeMultiplier', sa.Integer(), nullable=True),
    sa.Column('aggGroup', sa.Integer(), nullable=True),
    sa.Column('underSymbol', sa.String(), nullable=True),
    sa.Column('underSecType', sa.String(), nullable=True),
    sa.Column('marketRuleIds', sa.String(), nullable=True),
    sa.Column('secIdList', sa.String(), nullable=True),
    sa.Column('realExpirationDate', sa.String(), nullable=True),
    sa.Column('lastTradeTime', sa.String(), nullable=True),
    sa.Column('cusip', sa.String(), nullable=True),
    sa.Column('ratings', sa.String(), nullable=True),
    sa.Column('descAppend', sa.String(), nullable=True),
    sa.Column('bondType', sa.String(), nullable=True),
    sa.Column('couponType', sa.String(), nullable=True),
    sa.Column('callable', sa.Boolean(), nullable=True),
    sa.Column('putable', sa.Boolean(), nullable=True),
    sa.Column('coupon', sa.Integer(), nullable=True),
    sa.Column('convertible', sa.Boolean(), nullable=True),
    sa.Column('maturity', sa.String(), nullable=True),
    sa.Column('issueDate', sa.String(), nullable=True),
    sa.Column('nextOptionDate', sa.String(), nullable=True),
    sa.Column('nextOptionType', sa.String(), nullable=True),
    sa.Column('nextOptionPartial', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('contractId')
    )
    op.create_table('contracts',
    sa.Column('conId', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('secType', sa.String(), nullable=False),
    sa.Column('lastTradeDateOrContractMonth', sa.String(), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('right', sa.String(), nullable=True),
    sa.Column('multiplier', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('primaryExchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('derivativeSecTypes', sa.String(), nullable=True),
    sa.Column('localSymbol', sa.String(), nullable=True),
    sa.Column('tradingClass', sa.String(), nullable=True),
    sa.Column('includeExpired', sa.Boolean(), nullable=True),
    sa.Column('secIdType', sa.String(), nullable=True),
    sa.Column('secId', sa.String(), nullable=True),
    sa.Column('comboLegsDescrip', sa.String(), nullable=True),
    sa.Column('comboLegs', sa.String(), nullable=True),
    sa.Column('deltaNeutralContract', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('conId')
    )
    op.create_index(op.f('ix_contracts_currency'), 'contracts', ['currency'], unique=False)
    op.create_index(op.f('ix_contracts_derivativeSecTypes'), 'contracts', ['derivativeSecTypes'], unique=False)
    op.create_index(op.f('ix_contracts_exchange'), 'contracts', ['exchange'], unique=False)
    op.create_index(op.f('ix_contracts_primaryExchange'), 'contracts', ['primaryExchange'], unique=False)
    op.create_index(op.f('ix_contracts_secType'), 'contracts', ['secType'], unique=False)
    op.create_index(op.f('ix_contracts_symbol'), 'contracts', ['symbol'], unique=False)
    op.create_table('earning_estimate_reports',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('xml', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'insert_date')
    )
    op.create_table('exchanges',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('security_type', sa.String(), nullable=False),
    sa.Column('opening_hours', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('financial_snapshots',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('xml', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'insert_date')
    )
    op.create_table('financial_summaries',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('xml', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'insert_date')
    )
    op.create_table('fundamental_statements',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('xml', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'insert_date')
    )
    op.create_table('historical_data',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('secType', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('endDateTime', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('barSize', sa.String(), nullable=True),
    sa.Column('whatToShow', sa.String(), nullable=True),
    sa.Column('useRTH', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('barCount', sa.Integer(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    op.create_table('ownership_reports',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('xml', sa.String(), nullable=True),
    sa.Column('insert_date', sa.DateTime(), nullable=False),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'insert_date')
    )
    op.create_table('stocks',
    sa.Column('con_id', sa.Integer(), nullable=False),
    sa.Column('ib_symbol', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('product_description_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('con_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    op.drop_table('ownership_reports')
    op.drop_table('historical_data')
    op.drop_table('fundamental_statements')
    op.drop_table('financial_summaries')
    op.drop_table('financial_snapshots')
    op.drop_table('exchanges')
    op.drop_table('earning_estimate_reports')
    op.drop_index(op.f('ix_contracts_symbol'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_secType'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_primaryExchange'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_exchange'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_derivativeSecTypes'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_currency'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('contract_details')
    op.drop_table('calendar_reports')
    # ### end Alembic commands ###
