# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import proto.ib_client.request_data_pb2 as request__data__pb2


class RequestDataStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RequestContractDetails = channel.unary_unary(
        '/sendrequest.RequestData/RequestContractDetails',
        request_serializer=request__data__pb2.ContractDetailsRequest.SerializeToString,
        response_deserializer=request__data__pb2.Status.FromString,
        )
    self.RequestHistoricalData = channel.unary_unary(
        '/sendrequest.RequestData/RequestHistoricalData',
        request_serializer=request__data__pb2.HistoricalDataRequest.SerializeToString,
        response_deserializer=request__data__pb2.Status.FromString,
        )
    self.RequestFundamentalData = channel.unary_unary(
        '/sendrequest.RequestData/RequestFundamentalData',
        request_serializer=request__data__pb2.FundamentalDataRequest.SerializeToString,
        response_deserializer=request__data__pb2.Status.FromString,
        )


class RequestDataServicer(object):
  """The greeting service definition.
  """

  def RequestContractDetails(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestHistoricalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestFundamentalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RequestDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RequestContractDetails': grpc.unary_unary_rpc_method_handler(
          servicer.RequestContractDetails,
          request_deserializer=request__data__pb2.ContractDetailsRequest.FromString,
          response_serializer=request__data__pb2.Status.SerializeToString,
      ),
      'RequestHistoricalData': grpc.unary_unary_rpc_method_handler(
          servicer.RequestHistoricalData,
          request_deserializer=request__data__pb2.HistoricalDataRequest.FromString,
          response_serializer=request__data__pb2.Status.SerializeToString,
      ),
      'RequestFundamentalData': grpc.unary_unary_rpc_method_handler(
          servicer.RequestFundamentalData,
          request_deserializer=request__data__pb2.FundamentalDataRequest.FromString,
          response_serializer=request__data__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sendrequest.RequestData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
