# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fundamental_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fundamental_data.proto',
  package='fundamental_data',
  syntax='proto3',
  serialized_options=_b('\242\002\002FD'),
  serialized_pb=_b('\n\x16\x66undamental_data.proto\x12\x10\x66undamental_data\"\x07\n\x05\x45mpty\"C\n\rReportRequest\x12\r\n\x05stock\x18\x01 \x01(\t\x12\x12\n\nreportType\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"-\n\x1cLatestFinancialReportRequest\x12\r\n\x05stock\x18\x01 \x01(\t\"8\n\x0eReportMetaData\x12\x12\n\nreportDate\x18\x01 \x01(\t\x12\x12\n\ninsertDate\x18\x02 \x01(\t2\xd2\x01\n\x0f\x46undamentalData\x12K\n\rProcessReport\x12\x1f.fundamental_data.ReportRequest\x1a\x17.fundamental_data.Empty\"\x00\x12r\n\x1cGetLatestFinancialReportDate\x12..fundamental_data.LatestFinancialReportRequest\x1a .fundamental_data.ReportMetaData\"\x00\x42\x05\xa2\x02\x02\x46\x44\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='fundamental_data.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=51,
)


_REPORTREQUEST = _descriptor.Descriptor(
  name='ReportRequest',
  full_name='fundamental_data.ReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock', full_name='fundamental_data.ReportRequest.stock', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reportType', full_name='fundamental_data.ReportRequest.reportType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='fundamental_data.ReportRequest.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=120,
)


_LATESTFINANCIALREPORTREQUEST = _descriptor.Descriptor(
  name='LatestFinancialReportRequest',
  full_name='fundamental_data.LatestFinancialReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock', full_name='fundamental_data.LatestFinancialReportRequest.stock', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=167,
)


_REPORTMETADATA = _descriptor.Descriptor(
  name='ReportMetaData',
  full_name='fundamental_data.ReportMetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reportDate', full_name='fundamental_data.ReportMetaData.reportDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insertDate', full_name='fundamental_data.ReportMetaData.insertDate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=225,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ReportRequest'] = _REPORTREQUEST
DESCRIPTOR.message_types_by_name['LatestFinancialReportRequest'] = _LATESTFINANCIALREPORTREQUEST
DESCRIPTOR.message_types_by_name['ReportMetaData'] = _REPORTMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.Empty)
  })
_sym_db.RegisterMessage(Empty)

ReportRequest = _reflection.GeneratedProtocolMessageType('ReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTREQUEST,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.ReportRequest)
  })
_sym_db.RegisterMessage(ReportRequest)

LatestFinancialReportRequest = _reflection.GeneratedProtocolMessageType('LatestFinancialReportRequest', (_message.Message,), {
  'DESCRIPTOR' : _LATESTFINANCIALREPORTREQUEST,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.LatestFinancialReportRequest)
  })
_sym_db.RegisterMessage(LatestFinancialReportRequest)

ReportMetaData = _reflection.GeneratedProtocolMessageType('ReportMetaData', (_message.Message,), {
  'DESCRIPTOR' : _REPORTMETADATA,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.ReportMetaData)
  })
_sym_db.RegisterMessage(ReportMetaData)


DESCRIPTOR._options = None

_FUNDAMENTALDATA = _descriptor.ServiceDescriptor(
  name='FundamentalData',
  full_name='fundamental_data.FundamentalData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=228,
  serialized_end=438,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessReport',
    full_name='fundamental_data.FundamentalData.ProcessReport',
    index=0,
    containing_service=None,
    input_type=_REPORTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatestFinancialReportDate',
    full_name='fundamental_data.FundamentalData.GetLatestFinancialReportDate',
    index=1,
    containing_service=None,
    input_type=_LATESTFINANCIALREPORTREQUEST,
    output_type=_REPORTMETADATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FUNDAMENTALDATA)

DESCRIPTOR.services_by_name['FundamentalData'] = _FUNDAMENTALDATA

# @@protoc_insertion_point(module_scope)
