# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: listing.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='listing.proto',
  package='listing',
  syntax='proto3',
  serialized_options=_b('\242\002\007Listing'),
  serialized_pb=_b('\n\rlisting.proto\x12\x07listing\"\x07\n\x05\x45mpty\"\x1f\n\x0f\x45xchangeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\"\x1e\n\x0cStockRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"Q\n\x0cStockListing\x12\r\n\x05\x63onId\x18\x01 \x01(\x05\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x10\n\x08\x65xchange\x18\x04 \x01(\t2\x98\x01\n\x07Listing\x12J\n\x13GetStocksInExchange\x12\x18.listing.ExchangeRequest\x1a\x15.listing.StockListing\"\x00\x30\x01\x12\x41\n\x0fGetStockListing\x12\x15.listing.StockRequest\x1a\x15.listing.StockListing\"\x00\x42\n\xa2\x02\x07Listingb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='listing.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=33,
)


_EXCHANGEREQUEST = _descriptor.Descriptor(
  name='ExchangeRequest',
  full_name='listing.ExchangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='listing.ExchangeRequest.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=66,
)


_STOCKREQUEST = _descriptor.Descriptor(
  name='StockRequest',
  full_name='listing.StockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol', full_name='listing.StockRequest.symbol', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=98,
)


_STOCKLISTING = _descriptor.Descriptor(
  name='StockListing',
  full_name='listing.StockListing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conId', full_name='listing.StockListing.conId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='listing.StockListing.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='listing.StockListing.currency', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange', full_name='listing.StockListing.exchange', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=181,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ExchangeRequest'] = _EXCHANGEREQUEST
DESCRIPTOR.message_types_by_name['StockRequest'] = _STOCKREQUEST
DESCRIPTOR.message_types_by_name['StockListing'] = _STOCKLISTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'listing_pb2'
  # @@protoc_insertion_point(class_scope:listing.Empty)
  })
_sym_db.RegisterMessage(Empty)

ExchangeRequest = _reflection.GeneratedProtocolMessageType('ExchangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXCHANGEREQUEST,
  '__module__' : 'listing_pb2'
  # @@protoc_insertion_point(class_scope:listing.ExchangeRequest)
  })
_sym_db.RegisterMessage(ExchangeRequest)

StockRequest = _reflection.GeneratedProtocolMessageType('StockRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOCKREQUEST,
  '__module__' : 'listing_pb2'
  # @@protoc_insertion_point(class_scope:listing.StockRequest)
  })
_sym_db.RegisterMessage(StockRequest)

StockListing = _reflection.GeneratedProtocolMessageType('StockListing', (_message.Message,), {
  'DESCRIPTOR' : _STOCKLISTING,
  '__module__' : 'listing_pb2'
  # @@protoc_insertion_point(class_scope:listing.StockListing)
  })
_sym_db.RegisterMessage(StockListing)


DESCRIPTOR._options = None

_LISTING = _descriptor.ServiceDescriptor(
  name='Listing',
  full_name='listing.Listing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=184,
  serialized_end=336,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStocksInExchange',
    full_name='listing.Listing.GetStocksInExchange',
    index=0,
    containing_service=None,
    input_type=_EXCHANGEREQUEST,
    output_type=_STOCKLISTING,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetStockListing',
    full_name='listing.Listing.GetStockListing',
    index=1,
    containing_service=None,
    input_type=_STOCKREQUEST,
    output_type=_STOCKLISTING,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LISTING)

DESCRIPTOR.services_by_name['Listing'] = _LISTING

# @@protoc_insertion_point(module_scope)
