# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fundamental_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fundamental_data.proto',
  package='fundamental_data',
  syntax='proto3',
  serialized_options=b'\242\002\002FD',
  serialized_pb=b'\n\x16\x66undamental_data.proto\x12\x10\x66undamental_data\"\x07\n\x05\x45mpty\"P\n\x06Report\x12\r\n\x05stock\x18\x01 \x01(\t\x12\x12\n\nreportType\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\ninsertDate\x18\x04 \x01(\t\"\x1d\n\x0cStockRequest\x12\r\n\x05stock\x18\x01 \x01(\t\"8\n\x0eReportMetaData\x12\x12\n\nreportDate\x18\x01 \x01(\t\x12\x12\n\ninsertDate\x18\x02 \x01(\t\"\x1c\n\x08UpToDate\x12\x10\n\x08upToDate\x18\x01 \x01(\x08\x32\x99\x03\n\x0f\x46undamentalData\x12\x44\n\rProcessReport\x12\x18.fundamental_data.Report\x1a\x17.fundamental_data.Empty\"\x00\x12G\n\rGetAllReports\x12\x18.fundamental_data.Report\x1a\x18.fundamental_data.Report\"\x00\x30\x01\x12G\n\x0fGetLatestReport\x12\x18.fundamental_data.Report\x1a\x18.fundamental_data.Report\"\x00\x12\x62\n\x1cGetLatestFinancialReportDate\x12\x1e.fundamental_data.StockRequest\x1a .fundamental_data.ReportMetaData\"\x00\x12J\n\nIsUpToDate\x12\x1e.fundamental_data.StockRequest\x1a\x1a.fundamental_data.UpToDate\"\x00\x42\x05\xa2\x02\x02\x46\x44\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='fundamental_data.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=51,
)


_REPORT = _descriptor.Descriptor(
  name='Report',
  full_name='fundamental_data.Report',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock', full_name='fundamental_data.Report.stock', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reportType', full_name='fundamental_data.Report.reportType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='fundamental_data.Report.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insertDate', full_name='fundamental_data.Report.insertDate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=133,
)


_STOCKREQUEST = _descriptor.Descriptor(
  name='StockRequest',
  full_name='fundamental_data.StockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stock', full_name='fundamental_data.StockRequest.stock', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=164,
)


_REPORTMETADATA = _descriptor.Descriptor(
  name='ReportMetaData',
  full_name='fundamental_data.ReportMetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reportDate', full_name='fundamental_data.ReportMetaData.reportDate', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insertDate', full_name='fundamental_data.ReportMetaData.insertDate', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=222,
)


_UPTODATE = _descriptor.Descriptor(
  name='UpToDate',
  full_name='fundamental_data.UpToDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upToDate', full_name='fundamental_data.UpToDate.upToDate', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=252,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Report'] = _REPORT
DESCRIPTOR.message_types_by_name['StockRequest'] = _STOCKREQUEST
DESCRIPTOR.message_types_by_name['ReportMetaData'] = _REPORTMETADATA
DESCRIPTOR.message_types_by_name['UpToDate'] = _UPTODATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.Empty)
  })
_sym_db.RegisterMessage(Empty)

Report = _reflection.GeneratedProtocolMessageType('Report', (_message.Message,), {
  'DESCRIPTOR' : _REPORT,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.Report)
  })
_sym_db.RegisterMessage(Report)

StockRequest = _reflection.GeneratedProtocolMessageType('StockRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOCKREQUEST,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.StockRequest)
  })
_sym_db.RegisterMessage(StockRequest)

ReportMetaData = _reflection.GeneratedProtocolMessageType('ReportMetaData', (_message.Message,), {
  'DESCRIPTOR' : _REPORTMETADATA,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.ReportMetaData)
  })
_sym_db.RegisterMessage(ReportMetaData)

UpToDate = _reflection.GeneratedProtocolMessageType('UpToDate', (_message.Message,), {
  'DESCRIPTOR' : _UPTODATE,
  '__module__' : 'fundamental_data_pb2'
  # @@protoc_insertion_point(class_scope:fundamental_data.UpToDate)
  })
_sym_db.RegisterMessage(UpToDate)


DESCRIPTOR._options = None

_FUNDAMENTALDATA = _descriptor.ServiceDescriptor(
  name='FundamentalData',
  full_name='fundamental_data.FundamentalData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=255,
  serialized_end=664,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessReport',
    full_name='fundamental_data.FundamentalData.ProcessReport',
    index=0,
    containing_service=None,
    input_type=_REPORT,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAllReports',
    full_name='fundamental_data.FundamentalData.GetAllReports',
    index=1,
    containing_service=None,
    input_type=_REPORT,
    output_type=_REPORT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatestReport',
    full_name='fundamental_data.FundamentalData.GetLatestReport',
    index=2,
    containing_service=None,
    input_type=_REPORT,
    output_type=_REPORT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetLatestFinancialReportDate',
    full_name='fundamental_data.FundamentalData.GetLatestFinancialReportDate',
    index=3,
    containing_service=None,
    input_type=_STOCKREQUEST,
    output_type=_REPORTMETADATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IsUpToDate',
    full_name='fundamental_data.FundamentalData.IsUpToDate',
    index=4,
    containing_service=None,
    input_type=_STOCKREQUEST,
    output_type=_UPTODATE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FUNDAMENTALDATA)

DESCRIPTOR.services_by_name['FundamentalData'] = _FUNDAMENTALDATA

# @@protoc_insertion_point(module_scope)
