# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
from ibclient import grpc_service

import response_data_pb2 as response__data__pb2


class ResponseDataStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc_files.Channel.
    """
    self.SendContractDetails = channel.unary_unary(
        '/sendrequest.ResponseData/SendContractDetails',
        request_serializer=response__data__pb2.ContractDetailsResponse.SerializeToString,
        response_deserializer=response__data__pb2.Status.FromString,
        )
    self.HistoricalData = channel.unary_unary(
        '/sendrequest.ResponseData/HistoricalData',
        request_serializer=response__data__pb2.HistoricalDataResponse.SerializeToString,
        response_deserializer=response__data__pb2.Status.FromString,
        )
    self.FundamentalData = channel.unary_unary(
        '/sendrequest.ResponseData/FundamentalData',
        request_serializer=response__data__pb2.FundamentalDataResponse.SerializeToString,
        response_deserializer=response__data__pb2.Status.FromString,
        )


class ResponseDataServicer(object):
  """The greeting service definition.
  """

  def SendContractDetails(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc_service.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HistoricalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc_service.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FundamentalData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc_service.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ResponseDataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendContractDetails': grpc_service.unary_unary_rpc_method_handler(
          servicer.SendContractDetails,
          request_deserializer=response__data__pb2.ContractDetailsResponse.FromString,
          response_serializer=response__data__pb2.Status.SerializeToString,
      ),
      'HistoricalData': grpc_service.unary_unary_rpc_method_handler(
          servicer.HistoricalData,
          request_deserializer=response__data__pb2.HistoricalDataResponse.FromString,
          response_serializer=response__data__pb2.Status.SerializeToString,
      ),
      'FundamentalData': grpc_service.unary_unary_rpc_method_handler(
          servicer.FundamentalData,
          request_deserializer=response__data__pb2.FundamentalDataResponse.FromString,
          response_serializer=response__data__pb2.Status.SerializeToString,
      ),
  }
  generic_handler = grpc_service.method_handlers_generic_handler(
      'sendrequest.ResponseData', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
